### ISSUE TITLE
HTML vs Text value

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/create-html-element#2]
`create-html-element` only supports `innerHTML` via the prop `value`, whose name doesn't make this clear.

There should probably be a way to differentiate `innerHTML` from `textContent`, perhaps by using `html` and `text`, or literally `innerHTML` and `textContent`.

`textContent` would be escaped by `escape-goat`

**Comment by sindresorhus** [comment]
Removing the `value` option and replacing it with `html` and `text` options makes sense to me.
