### ISSUE TITLE
rollupjs build returning an error @ html-tags sub-package

### ISSUE THREAD

**Issue by atherdon** [sindresorhus/create-html-element#6]
Hi @sindresorhus, nice to meet you - i'm a huge fan of your work.

today I tried to install `create-html-element` pkg in my project and get an error from Rollupjs binder.
not sure if it should be fixed here, but want to let you know.

trace that I get in my CLI
```
[!] Error: 'default' is not exported by node_modules/html-tags/html-tags-void.json, imported by /**/node_modules/html-tags/html-tags-void.json?commonjs-proxy
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
/**/node_modules/html-tags/html-tags-void.json?commonjs-proxy (1:9)
1: export { default } from "/**/node_modules/html-tags/html-tags-void.json";
            ^
Error: 'default' is not exported by node_modules/html-tags/html-tags-void.json, imported by /**/node_modules/html-tags/html-tags-void.json?commonjs-proxy
    at error (/**/node_modules/rollup/dist/shared/rollup.js:198:30)
    
```

I assume it's related to this line: https://github.com/sindresorhus/create-html-element/blob/main/index.js#L2

**Comment by sindresorhus** [comment]
It looks like a problem with Rollup. You may need to enable JSON support in some Rollup config.

**Comment by atherdon** [comment]
thank you - will try right now

**Comment by atherdon** [comment]
it was an issue with my project setup, thank you! 
i`m a huge fan
